version: "2"
services:
  web:
    image: test:latest
    ports:
      - "5000:5000"
    links:
      - dbserver
  dbserver:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
